### ISSUE TITLE
BUG: order initialization should have a credit_card arg

### ISSUE THREAD

**Issue by peterskipper** [gamagori/pizzapi#22] opened 2018-01-26 20:15 UTC
The README example(s) order.pay_with(card) and order.place(card) do not currently work because an order object expects to have a credit_card attribute. The function signature for order should have a credit_card attribute set to None:

def __init__(self, store, customer, address, credit_card=None, country=COUNTRY_USA):

And then the pay_with method should check if self.credit_card is None

I can contribute a fix if you'd like!

**Comment by aluttik** [comment] 2018-01-30 07:35
Sure that'd be great, thanks

**Comment by gamagori** [comment] 2018-02-06 03:54
@peterskipper Hey, Peter! I pulled in a commit yesterday that fixes this. See [here].(https://github.com/gamagori/pizzapi/blob/master/pizzapi/order.py#L118-L128)

Rather than initialize the Order object with a card (I don't think you need it to call pay_with), I just modified the calls that use credit_card to use the card object that the caller passes in. 

I'm going to close this issue out - let me know if you have any objections.

**Closed by gamagori** 2018-02-06 03:54 UTC

**Comment by peterskipper** [comment] 2018-02-06 16:45
Thanks for responding!  I'm a little bit concerned, though I may not understand the fix.  It looks like pay_with uses card=False by default, and that in turn causes a 'Cash' payment to be sent?  Won't that cause me to accidentally order a pizza with cash when I'm just testing my code out with pay_with?

**Comment by gamagori** [comment] 2018-02-06 17:10
@peterskipper Excellent question! [pay_with](https://github.com/gamagori/pizzapi/blob/master/pizzapi/order.py#106) and [place](https://github.com/gamagori/pizzapi/blob/master/pizzapi/order.py#L99) use two distinct (but similar-looking) URL endpoints. 

You can see the actual endpoints in the urls module [here](https://github.com/gamagori/pizzapi/blob/master/pizzapi/urls.py#L20-L21). There's one API for getting a price for the order, and then another one for actually placing it. So, you could repeatedly price your order as you add toppings etc, and then place it once you've confirmed your price looks as intended. 

Actually, our current request to the price_url doesn't even use the card object you pass in - I'm not sure why this is. Maybe the price changes if you order by card vs cash? I'll add this to my to-do list for next time I order pizza.
